#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Access Virus TI2 5.1.3.0 Complete MIDNAM Generator
Generates a complete MIDNAM file with all factory presets
"""

# Alle Presets
PRESETS = {
    'RAM-A': [
        'HyprNochBC', 'Fimplex HS', 'Veldisa BC', 'Trib@lGruv', 'TuchAcidBC', 'PhatlandBC', 'TrntBassBC', 'SnowfallBC', 'SqrBass XM', 'LA Lore HS', 'Lofibrk NM', 'NinthHvnSV', 'MethLab M', 'YouWish HS', 'RandArp BC', 'MWQuant BC', 'FunkTripMS', 'SeaThreeHS', 'ComboBazAV', 'ColdMetlBC', 'OvertureCK', 'LdGr@nForm', 'GarBass8BC', 'SevnthWvBC', 'Ti|Bell SV', 'LaserHrpPK', 'FrmntPadRD', 'Bellt@ble', 'AcidBath M', 'Bubble PX', 'Stabber HS', 'ZarndorfHS', 'Phazzah HS', 'GeoSpherBC', 'Gondor1 HS', 'WoodwardHS', 'Blingo HS', 'ChordataHS', 'bsDamnHot@', 'D   O', 'AutoKit BC', 'MySistarPX', 'EarlMbleOM', 'AudienceHS', 'Boogion HS', 'DuckwardHS', 'Gotham HS', 'FallAprtRD', 'Bedlam BC', 'IntoTheVRD', 'Pstyro2 HS', 'HalfliteBC', 'V+ FattyHS', 'ScratchyPS', 'L.Mays2 CC', 'SidKid HS', 'TardisB HS', 'HardwearBC', 'HellGateBC', 'Matter JL', 'Choir2 HS', 'ProWeed HS', 'glassdance', 'ChiffyPop@', 'Metalic SV', 'Modulow HS', 'MultiT@lke', 'MushKrakAV', 'MwaveLd BB', 'Nazty AV', 'ODC SV', 'OiOiBassMS', 'Omnipeg SV', 'OutburstBC', 'Pad+2.3 m@', 'Padder3 BB', 'ParadiseSV', 'pdSurfW@ve', 'PhatlandBC', 'Pitchy AV', 'PiterFM AV', 'PlastoneMS', 'Poly5thmi@', 'PowerfulAV', 'ProdLd1 BC', 'ProjectXSV', 'PsyAcid AV', 'PunkLead @', 'PureEvilAV', 'Quantum JL', 'R2D2MW AV', 'RandArpBC', 'RateSweep@', 'Reverse AV', 'RezoBassMS', 'RinkDingAV', 'RolinTB AV', 'Scratch AV', 'Shortie AV', 'Skreamy AV', 'Smoky303SV', 'SnowfallBC', 'Square AV', 'Step64 MS', 'Sweepz@', 'Syncer BC', 'TardisB HS', 'TchnolgcMS', 'TeeZee SV', 'Termen AV', 'Toucherv@L', 'Tr@inspott', 'TriblZapMS', 'TrntBassBC', 'TuchAcidBC', 'UltraSawBC', 'Use Me 1SV', 'Vanish MS', 'Vertigo SV', 'VocLead AV', 'Voxiter MS', 'Whitebs SV', 'WidePad MS', 'WindSeq AV', 'X-Mod MS', 'YamahFB1MS', 'ZingBassHS', '-Init-'
    ],
    'RAM-B': [
        'AcidBath M', 'Acidia AV', 'Anaconda M', 'Aphex RD', 'BadBrain M', 'BadmouthBC', 'BagHead M', 'BarFight M', 'BassSoupBC', 'Basting zs', 'Beltram M', 'Caustic BC', 'Chimp', 'Codine M', 'ColdMetlBC', 'Comput8 RD',  'ConfusiaRD', 'Cytherea M', 'DarkModrRD', 'DarkTombSV', 'DeadlySubM', 'DeepSouthM', 'DigiGrv XM', 'DigiSaw BC', 'DirtyPlsBC', 'DistBassXM', 'Distort AV', 'DistortaXM', 'DivngBelBC', 'Donky BC', 'Drano M', 'DriveBy M', 'EBMBass1XM', 'EBMBass2XM', 'ElectrR2BC', 'eTalking M', 'EXLightsRD', 'EyePatch M', 'Fearless M', 'Felon M', 'FMeUp BC', 'FormerloBC', 'Front242XM', 'GamelandRD', 'Gifted M', 'GrokBassBC', 'GrokLeadBC', 'HailMary M', 'HardwearBC', 'Hazmat M', 'HellGateBC', 'Hideout M', 'HomeAloneM', 'HumanFly M', 'IconArp XM', 'IOC 3-4 XM', 'K-Hole M', 'KraftArpXM', 'Lacer8r BC', 'LectroLdXM', 'Lemon M', 'Manga BC', 'MegaEvilAV', 'MeltSyn XM', 'Metelec BC', 'MethLab M', 'Mongo M', 'MWQuant BC', 'Ninty JL', 'NoizBassXM', 'NuSkool jh', 'O My GodXM', 'Omen M', 'OverblowBC', 'Pad 8bitXM', 'Phantom M', 'PhasrArpXM', 'Phobic MH', 'PinHead M', 'Plang BC', 'Pluka zs', 'PolutionBC', 'PopTart M', 'PrismPadRD', 'Pro1-FX XM', 'Prongo M', 'Punchit2SV', 'Randy BC', 'Remus M', 'Revkick NM', 'RezPad XM', 'Ringie SV', 'RinkDingAV', 'RollDeep M', 'S9GrooveXM', 'Sandman M', 'SatuBassBC', 'ScrmArp XM', 'SinCity M', 'Sinus9 XM', 'Slash BC', 'SpasDrv zs', 'SqrArp2 XM', 'StarDustM', 'StaticFMRD', 'Sub-W DC', 'SuckMe BC', 'SupaSyk BC', 'SwellPadRD', 'Syrys BC', 'Ti|Bell SV', 'Torus BC', 'Transit M', 'TranzBasXM', 'Tycoon M', 'U F O XM', 'UltraArpMH', 'Vacuum JL', 'Vaughn M', 'Vengance M', 'Voltage M', 'WarpCuspRD', 'WastelndBC', 'Xaris BC', 'Xianum BC', 'XMorphLdXM', 'XMorphLpXM', 'YuckMouthM'
    ],
    'RAM-C': [
        'Aah-Vln HS', 'Alead BC', 'BadCntaxHS', 'BellBoy BC', 'Bellt@ble', 'bsEX8000 @', 'BsTaurean@', 'BublLeadjh', 'CharactrMS', 'Choir2 HS', 'Cremoma HS', 'D50Lead MS', 'DreBeat jh', 'DWBelComp@', 'DX-Pno1 HS', 'DX-Pno2 HS', 'DX-Pno3 HS', 'E-Grand HS', 'EP+Faze HS', 'EP3DogNyt@', 'EPZeply M@', 'ESQbass MH', 'Farfisa PK', 'V+ FattyHS', 'FlagshipHS', 'Floooot HS', 'Flutoon HS', 'qP', 'FunkLd-2SM', 'FunkLd-3SM', 'FunkLd-4SM', 'FunnyLd BC', 'GarBass8BC', 'GertLead @', 'Ham&X HS', 'HardTB AV', 'Harpsie HS', 'HedHuntrBC', 'HolyVrs JL', 'Horror2 jh', 'Howner RP', 'HPSqrLd BC', 'ImpOsc03HS', 'JamMini HS', 'JP Bass MS', 'L.Mays1 CC', 'L.Mays2 CC', 'LA Lore HS', 'LaserHrpPK', 'Ld-OB 82 @', 'Ld4Quincy@', 'LegacybsSV', 'LetsSyncM@', 'LordOrg HS', 'LostLeadHS', 'M@trix1000', 'MarkOne HS', 'MiniBS-2SM', 'MiniBS-5SM', 'Noog 4P @', 'Nylon BC', 'OB 8 CC', 'ObiFanf HS', 'OutaspceNM', 'OvertureCK', 'P-Organ RP', 'P@rtials 1', 'P@rtials 2', 'PataFiz HS', 'PeaceOrgHS', 'Phloid HS', 'Pianu BC', 'PickUp HS', 'Pit-Str HS', 'PlecBassHS', 'PPG Comp @', 'PPG Syn PS', 'PPGsaws BC', 'PPG TI jh', 'Pro-12 RP', 'ProWeed HS', 'Pstyro2 HS', 'PWM Pad BC', 'Quintesnc@', 'RezBass HS', 'Rigby2 HS', 'SeaThreeHS', 'ShwrScneBC', 'SidKid HS', 'SinSolo HS', 'SlipShotHS', 'SmoothBsBC', 'Snakeye HS', 'Stabber HS', 'StTheoryBC', 'Synthar HS', 'Tomita J', 'TuvaWeelHS', 'UKG2 BC', 'VC ACID BC', 'VelFmBasBC', 'WtrSprtsjh', 'X-Files PS', 'Xyrimba HS', 'YouWish HS', 'Arp-BD2 RP', 'AutoShkeBC', 'Claps 1 BC', 'Cow 808 BC', 'Dis-BD RP', 'DistKickBC', 'ETom2002M@', 'FlatHat HS', 'GateRim HS', 'MW Kk>HtBC', 'NewSnareBC', 'PercMorfBC', 'PercMrf2BC', 'PhatKickBC', 'RezDrum BC', 'RimShot BC', 'SimSyn HS', 'SnrRoll BC', 'Tambo BC', 'TecKick MH', '>>INPUT<<', '-START-', '-INIT-'
    ],
    'RAM-D': [
        'AbstractRD', 'AerialPdRD', 'AlienChtRD', 'Aliens MH', 'Bangesh RD', 'BarbieriMH', 'Bedlam BC', 'BelisimoBC', 'BellTineRD', 'Bl@kCopter', 'BlinkLEDRD', 'BlueSporRD', 'Bore@lis', 'Bubble pix', 'Bubbles RD', 'BurkSyn RD', 'CalmNiteRD', 'Chimera RD', 'ChoirBelBC', 'Cicadia BC', 'CloudPadRD', 'CrystlFXRD', 'CyborgFXRD', 'D=CM+1 HS', 'DeepBlueBC', 'DeepColvRD', 'Dehjex MH', 'Deinos @', 'DnThePanBC', 'Dreams MH', 'DropletsRD', 'DualiTI BC', 'DustFld RD', 'E-tron RD', 'EmpericlRD', 'Euqria BC', 'EXLightsRD', 'Expanse BC', 'F-Motor RD', 'FallAprtRD', 'FiboPad BC', 'Flutter RD', 'FMMadnesRD', 'FMOptersRD', 'FMScape RD', 'Freno BC', 'FrmntPadRD', 'G Sines BC', 'GamelandRD', 'GeoSpherBC', 'Gissy RD', 'Glacier BC', 'GlitchFXRD', 'GloWormsBC', 'GlsBelPdBC', 'GlsTinesRD', 'Gorogro NM', 'GranBelsBC', 'GrnVoco BC', 'HalfliteBC', 'HansStr RD', 'Heaven JL', 'HrorSineRD', 'HypnechoBC', 'IcefieldMH', 'Insects RD', 'Interia RD', 'IntoTheVRD', 'InvisiPdBC', 'Ioead BC', 'Kascade RD', 'Korgi BC', 'Majiko BC', 'Melene BC', 'MetaLab RD', 'Misty BC', 'ModifierMH', 'ModulaFXRD', 'Mongoro NM', 'MoonbugsBC', 'Nanules BC', 'Nenoa BC', 'NeoSphr2BC', 'NextOrbit@', 'Nu Vue pix', 'OceanPadRD', 'OldTimesRD', 'Peace BC', 'Phobic MH', 'Plasma RD', 'PointCldRD', 'PulsFadeBC', 'ReflxshnBC', 'RezbiantBC', 'RingBlotRD', 'RndmMessRD', 'RubberFXRD', 'SCIspensBC', 'Secret AV', 'Sekur BC', 'SensePadRD', 'SeqSweepBC', 'SevnthWvBC', 'Shifted BC', 'Sighing BC', 'Simsuki BC', 'Soft pix', 'SoftTch RD', 'SpAcEvOx @', 'SpceRdioRD', 'Spooked BC', 'StarLiteRD', 'SummerPdRD', 'SunDial RD', 'SwampFX RD', 'ThebuTI BC', 'TransmitRD', 'TwilightRD', 'Twisted RD', 'the deep >', 'thick >', 'tonic >', 'twisted >', 'unleaded >', 'up&down >', 'uva acida>', 'vintage >', 'watercop >'
    ],
    'ROM-A': [
        '3-Dumm HS', 'AsiaVoizAV', 'Atx BassMS', 'Bad Pop MS', 'BassLeadBB', 'Beast AV', 'BeautiflJL', 'BigBass AV', 'BigPh@rma', 'BionicleSV', 'BombasdrBC', 'BoomahMgSV', 'BothEndsBC', 'BsMoovin\'@', 'Chaos AV', 'Chitin HS', 'ClokRampBC', 'Coldtab SV', 'ComboBazAV', 'CosmicA SV', 'Cozze SV', 'DarkliteSV', 'DarktrnzSV', 'DeepSwllJL', 'Detuned AV', 'Distort AV', 'DownliftFX', 'DryThrthSV', 'EnvBass BC', 'FftyFftyJL', 'Fimplex HS', 'FiveCentSV', 'FlangMW AV', 'Flapjak HS', 'FlatFat AV', 'Flylead BC', 'FunkTripMS', 'Genosis MS', 'GlobalDJMS', 'GrokBassBC', 'GrokLeadBC', 'HiScore MS', 'Hog NB', 'Hoho. JL', 'Hollow JL', 'Hows SV', 'HPSqrLd BC', 'HypassorBC', 'HyprNtchBC', 'Karlos AV', 'KetamineMS', 'KewlPlugAV', 'KickItBsBB', 'Kofi-B HS', 'Krutoi AV', 'Lately MS', 'LdGr@nForm', 'LDS-Lab HS', 'LegacybsSV', 'LoGrooveMS', 'Matter JL', 'Metalic SV', 'Modulow HS', 'MultiT@lke', 'Mushi AV', 'MushKrakAV', 'MwaveLd BB', 'Nazty AV', 'ODC SV', 'OiOiBassMS', 'Omnipeg SV', 'OutburstBC', 'Pad+2.3 m@', 'Padder3 BB', 'ParadiseSV', 'pdSurfW@ve', 'PhatlandBC', 'Pitchy AV', 'PiterFM AV', 'PlastoneMS', 'Poly5thmi@', 'PowerfulAV', 'ProdLd1 BC', 'ProjectXSV', 'PsyAcid AV', 'PunkLead @', 'PureEvilAV', 'Quantum JL', 'R2D2MW AV', 'RandArp BC', 'RateSweep@', 'Reverse AV', 'RezoBassMS', 'RinkDingAV', 'RolinTB AV', 'Ruffcut HS', 'Scratch AV', 'Shortie AV', 'Skreamy AV', 'Smoky303SV', 'SnowfallBC', 'Square AV', 'Step64 MS', 'Sweepz@', 'Swingy PX', 'Syncer BC', 'TardisB HS', 'TchnolgcMS', 'TeeZee SV', 'Termen AV', 'Toucherv@L', 'Tr@inspott', 'TriblZapMS', 'TrntBassBC', 'TuchAcidBC', 'UltraSawBC', 'Use Me 1SV', 'Vanish MS', 'Vertigo SV', 'VocLead AV', 'Voxiter MS', 'Whitebs SV', 'WidePad MS', 'WideSAW AV', 'WindSeq AV', 'X-Mod MS', 'YamahFB1MS', 'ZingBassHS'
    ],
    'ROM-B': [
        'AcidBath M', 'Acidia AV ', 'Anaconda M', 'Aphex RD  ', 'ArpAcid BC', 'BadBrain M', 'BadmouthBC', 'BagHead M ', 'BarFight M', 'BassSoupBC', 'Basting zs', 'Beltram M ', 'Brkdwn BC ', 'Caustic BC', 'Chimp M   ', 'Codine M  ', 'ColdMetlBC', 'Comput8 RD', 'ConfusiaRD', 'Cytherea M', 'DarkModrRD', 'DarkTombSV', 'DeadlySubM', 'DeepSouthM', 'DigiGrv XM', 'DigiSaw BC', 'DirtyPlsBC', 'DistBassXM', 'Distort AV', 'DistortaXM', 'DivngBelBC', 'Donky BC  ', 'Drano M   ', 'DriveBy M ', 'EBMBass1XM', 'EBMBass2XM', 'ElectrR2BC', 'eTalking M', 'EXLightsRD', 'EyePatch M', 'Fearless M', 'Felon M   ', 'FMeUp BC  ', 'FormerloBC', 'Front242XM', 'GamelandRD', 'Gifted M  ', 'HailMary M', 'HardwearBC', 'Hazmat M  ', 'HellGateBC', 'Hideout M ', 'HomeAloneM', 'HumanFly M', 'IconArp XM', 'IOC 3-4 XM', 'K-Hole M  ', 'KraftArpXM', 'Lacer8r BC', 'LectroLdXM', 'Lemon M   ', 'Manga BC  ', 'MegaEvilAV', 'MeltSyn XM', 'Metelec BC', 'MethLab M ', 'Mongo M   ', 'MWQuant BC', 'Ninty JL  ', 'NoizBassXM', 'NuSkool jh', 'O My GodXM', 'Omen M    ', 'OverblowBC', 'Pad 8bitXM', 'Phantom M ', 'PhasrArpXM', 'Phobic MH ', 'PinHead M ', 'Plang BC  ', 'Pluka zs  ', 'PolutionBC', 'PopTart M ', 'PrismPadRD', 'Pro1-FX XM', 'Prongo M  ', 'Punchit2SV', 'Randy BC  ', 'Remus M   ', 'Revkick NM', 'RezPad XM ', 'Ringie SV ', 'RinkDingAV', 'RollDeep M', 'S9Groov1XM', 'Sandman M ', 'SatuBassBC', 'ScrmArp XM', 'SinCity M ', 'Sinus9 XM ', 'Slash BC  ', 'SpasDrv zs', 'SqrArp2 XM', 'StarDust M', 'StaticFMRD', 'Sub-W DC  ', 'SuckMe BC ', 'SupaSyk BC', 'SwellPadRD', 'Syrys BC  ', 'Ti|Bell SV', 'Torus BC  ', 'Transit M ', 'TranzBasXM', 'Tycoon M  ', 'U F O XM  ', 'UltraArpMH', 'Vacuum JL ', 'Vaughn M  ', 'Vengance M', 'Tutorial 1', 'Tutorial 2', 'Tutorial 3', 'Tutorial 4', 'Tutorial 5', '>>INPUT<< ', '-START-   ', '-INIT-    '
    ],
    'ROM-C': [
        'Aah-Vln HS', 'Alead BC  ', 'AndromdaHS', 'BadCntaxHS', 'BellBoy BC', 'Bellt@ble ', 'bsEX8000 @', 'BsTaurean@', 'BublLeadjh', 'CharactrMS', 'Choir2 HS ', 'Cremoma HS', 'D50Lead MS', 'DreBeat jh', 'DWBelComp@', 'DX-Pno1 HS', 'DX-Pno2 HS', 'DX-Pno3 HS', 'E-Grand HS', 'EP+Faze HS', 'EP3DogNyt@', 'EPZeply M@', 'ESQbass MH', 'ETom2002M@', 'Farfisa PK', 'FlagshipHS', 'Floooot HS', 'Flutoon HS', 'Forever M ', 'FunkLd-1SM', 'FunkLd-2SM', 'FunkLd-3SM', 'FunkLd-4SM', 'FunnyLd BC', 'GarBass8BC', 'GertLead @', 'Ham&X HS  ', 'HardTB AV ', 'Harpsie HS', 'HedHuntrBC', 'HolyVrs JL', 'Horror2 jh', 'Howner RP ', 'HyprHarpBC', 'ImpOsc03HS', 'JamMini HS', 'JP Bass MS', 'L.Mays1 CC', 'L.Mays2 CC', 'LA Lore HS', 'LaserHrpPK', 'Ld-OB 82 @', 'Ld4Quincy@', 'LegacybsSV', 'LetsSyncM@', 'LordOrg HS', 'LostLeadHS', 'M@trix1000', 'MarkOne HS', 'MiniBS-2SM', 'MiniBS-5SM', 'Noog 4P @ ', 'Nylon BC  ', 'OB 8 CC   ', 'ObiFanf HS', 'OutaspceNM', 'OvertureCK', 'P-Organ RP', 'P@rtials 1', 'P@rtials 2', 'PataFiz HS', 'PeaceOrgHS', 'PercMorfBC', 'PercMrf2BC', 'Phloid HS ', 'Pianu BC  ', 'PickUp HS ', 'Pit-Str HS', 'PlecBassHS', 'PPG Comp @', 'PPG Syn PS', 'PPG TI jh ', 'PPGsaws BC', 'Pro-12 RP ', 'ProWeed HS', 'Pstyro2 HS', 'PWM Pad BC', 'Quintesnc@', 'RezBass HS', 'RezDrum BC', 'Rigby2 HS ', 'SeaThreeHS', 'ShwrScneBC', 'SidKid HS ', 'SinSolo HS', 'SlipShotHS', 'SmoothBsBC', 'Snakeye HS', 'Stabber HS', 'StTheoryBC', 'Synthar HS', 'Tomita J  ', 'TuvaWeelHS', 'UKG2 BC   ', 'V+ FattyHS', 'VC ACID BC', 'VelFmBasBC', 'WtrSprtsjh', 'X-Files PS', 'Xyrimba HS', 'YouWish HS', 'Arp-BD2 RP', 'AutoShkeBC', 'Claps 1 BC', 'Cow 808 BC', 'Dis-BD RP ', 'DistKickBC', 'FlatHat HS', 'GateRim HS', 'MW Kk>HtBC', 'NewSnareBC', 'PhatKickBC', 'RimShot BC', 'SimSyn HS ', 'SnrRoll BC', 'Tambo BC  ', 'TecKick MH', '-INIT-    '
    ],
    'ROM-D': [
        'AbstractRD', 'AerialPdRD', 'AlienChtRD', 'Aliens MH ', 'Bangesh RD', 'BarbieriMH', 'Bedlam BC ', 'BelisimoBC', 'BellTineRD', 'Bl@kCopter', 'BlinkLEDRD', 'BlueSporRD', 'Bore@lis  ', 'Bubble pix', 'Bubbles RD', 'BurkSyn RD', 'CalmNiteRD', 'Chimera RD', 'ChoirBelBC', 'Cicadia BC', 'CloudPadRD', 'CrystlFXRD', 'CyborgFXRD', 'D=CM+1 HS ', 'DeepBlueBC', 'DeepColvRD', 'Dehjex MH ', 'Deinos @  ', 'DnThePanBC', 'Dreams MH ', 'DropletsRD', 'DualiTI BC', 'DustFld RD', 'E-tron RD ', 'EmpericlRD', 'Euqria BC ', 'Expanse BC', 'F-Motor RD', 'FallAprtRD', 'FiboPad BC', 'Flutter RD', 'FMMadnesRD', 'FMOptersRD', 'FMScape RD', 'Freno BC  ', 'FrmntPadRD', 'G Sines BC', 'GamelandRD', 'GeoSpherBC', 'Gissy RD  ', 'Glacier BC', 'GlitchFXRD', 'GloWormsBC', 'GlsBelPdBC', 'GlsTinesRD', 'Gorogro NM', 'GranBelsBC', 'GrnVoco BC', 'HalfliteBC', 'HansStr RD', 'Heaven JL ', 'HrorSineRD', 'HypnechoBC', 'IcefieldMH', 'Insects RD', 'Interia RD', 'IntoTheVRD', 'InvisiPdBC', 'Ioead BC  ', 'Kascade RD', 'Korgi BC  ', 'Majiko BC ', 'Melene BC ', 'MetaLab RD', 'Misty BC  ', 'ModifierMH', 'ModulaFXRD', 'Mongoro NM', 'MoonbugsBC', 'Nanules BC', 'Nenoa BC  ', 'NeoSphr2BC', 'NextOrbit@', 'Nu Vue pix', 'OceanPadRD', 'OldTimesRD', 'Peace BC  ', 'PearlPadRD', 'Phobic MH ', 'Plasma RD ', 'PointCldRD', 'PulsFadeBC', 'ReflxshnBC', 'RezbiantBC', 'RingBlotRD', 'RndmMessRD', 'RubberFXRD', 'SCIspensBC', 'Secret AV ', 'Sekur BC  ', 'SensePadRD', 'SeqSweepBC', 'SevnthWvBC', 'Shifted BC', 'Sighing BC', 'Simsuki BC', 'Soft pix  ', 'SoftTch RD', 'SpAcEvOx @', 'SpceRdioRD', 'Spooked BC', 'StarLiteRD', 'SummerPdRD', 'SunDial RD', 'SwampFX RD', 'ThebuTI BC', 'TransmitRD', 'TwilightRD', 'Twisted RD', 'Utopia*pix', 'Vormph RD ', 'wArp BC   ', 'Wavella BC', 'WMD pix   ', 'WrathFX RD', 'WT S+H BC ', 'WtrTinesRD', '-INIT-    '
    ],
    'ROM-E': [
        '80´sStabBC', 'AutoHat BC', 'BanjArp BC', 'BassArp BC', 'BassMan1BC', 'BassMan2BC', 'Beans BC  ', 'BigLead BC', 'Bite Me BC', 'BluBotl BC', 'BottlPadBC', 'BriteArpBC', 'Burbler BC', 'BuzzBassBC', 'CheezMe BC', 'Claps 2 BC', 'ClaviKeyBC', 'CompressBC', 'DelivrncBC', 'DirtLeadBC', 'DirtyPlsBC', 'DublArp BC', 'Electro1BC', 'ElectrR1BC', 'Epitaph BC', 'FlwLead BC', 'Fritter BC', 'FunkMamaBC', 'FunnyLd BC', 'FuzzFM BC ', 'GritBas1BC', 'GritBas2BC', 'HardBassBC', 'HardLeadBC', 'HldPdHatBC', 'HoloArp BC', 'HoloBassBC', 'HypaFlowBC', 'HypaHypeBC', 'Hysaws BC ', 'Klang BC  ', 'Klunk BC  ', 'KraftAr1BC', 'KraftAr2BC', 'KraftAr3BC', 'KraftAr4BC', 'KraftAr5BC', 'KraftAr6BC', 'LatentBsBC', 'LktroArpBC', 'LktroPlkBC', 'LoFiHit BC', 'Monday BC ', 'Mooky BC  ', 'MPScreamBC', 'MuteArp BC', 'MWBrass BC', 'Navel BC  ', 'NewGBassBC', 'NiceKeysBC', 'NotchPlsBC', 'NotchSawBC', 'OnRun BC  ', 'PanLid1 BC', 'PanLid2 BC', 'PercArp1BC', 'PercArp2BC', 'PercArp3BC', 'PercMorfBC', 'PercMrf2BC', 'PipSqw3kBC', 'PizzArp BC', 'PlukArp1BC', 'PlukArp2BC', 'PlukTremBC', 'PPGdual BC', 'Pulsaw BC ', 'RezArp1 BC', 'RezArp2 BC', 'RezDrum BC', 'RezPerc BC', 'RingLedrBC', 'RingOrgnBC', 'SatKick BC', 'Saucer BC ', 'SawMorf BC', 'Sear BC   ', 'ShortBasBC', 'ShortSawBC', 'SineZap BC', 'Slinka BC ', 'SnareMrfBC', 'SoftArp1BC', 'SoftArp2BC', 'SoftArp3BC', 'Sqr Arp BC', 'StabLeadBC', 'StacArp1BC', 'StacArp2BC', 'Stick BC  ', 'SweetFA BC', 'Sweptre BC', 'SykBassBC ', 'SyncArp1BC', 'SyncloneBC', 'Teknoid BC', 'ThickPadBC', 'ThinPad BC', 'Thryba BC ', 'TinFoil BC', 'TremStabBC', 'TuchFunkBC', 'VA1 BC    ', 'VA2 BC    ', 'VA3 BC    ', 'VA4 BC    ', 'VanOrch BC', 'VC ACID BC', 'VelbendaBC', 'VelBouncBC', 'VoxOct BC ', 'VoxWave BC', 'WarmUp BC ', 'WarpLeadBC', 'WetArp BC ', 'WetBass BC', 'Whistle BC', 'Zap BC    '
    ],
    'ROM-F': [
        'T I BC    ', '2DaHillsBB', 'Alpad1 BB ', 'Ambient1AV', 'ArcScan RD', 'ArpDreamBB', 'AsbestosHS', 'Basspad NM', 'Batkick NM', 'BidaZ FXBB', 'BigPipe BC', 'Bisnaga PX', 'BlocBassRD', 'Blop PX   ', 'BOCSynthRD', 'BrokenFXRD', 'BumFluf BC', 'C´mon! PX ', 'Cables BC ', 'CaveinseNM', 'Clouds BC ', 'Coolado PX', 'CrlySythRD', 'Current NM', 'CylonPe@ce', 'D bomb PX ', 'DaliaSynRD', 'DataChrdRD', 'Deathead @', 'Deelite NM', 'DistantXRD', 'DustStrmRD', 'E-FasLd BB', 'ElectrixRD', 'EnergyupNM', 'EvilEverAV', 'Fate NM   ', 'Feedbak AV', 'FlowablaRD', 'FrmCmp2 BB', 'FrogBassRD', 'Fula PX   ', 'GamegirlPX', 'GohomeseNM', 'GrandPixRD', 'Granite HS', 'GranularAV', 'GritFunkBC', 'Ground NM ', 'Guzzi HS  ', 'HardshelNM', 'HarshArpBC', 'Humania RD', 'IndstralNM', 'Justice PX', 'KaosPad AV', 'Kilter2 HS', 'Launch BC ', 'LndscapeNM', 'LzrDidj BC', 'Mad8ve NM ', 'Madmodx NM', 'Magish PX ', 'MalfunctRD', 'MetafunkNM', 'Metalo NM ', 'MetlFunkBC', 'MicrotecRD', 'Mod-Mod RD', 'Modular RD', 'ModulePdRD', 'MoodBelsRD', 'NasTI BC  ', 'NaturPadRD', 'Nazgul PX ', 'NewkLeadBC', 'Nudisco NM', 'Omen NM   ', 'Opener1 BB', 'Opener2 BB', 'PandemonBC', 'ParanoiaNM', 'PlsarSynRD', 'PolytechNM', 'Pulsing RD', 'ReptlPadRD', 'Revacid NM', 'RingkickNM', 'RusticBsRD', 'S&HErrorRD', 'SawasawaNM', 'Screamy AV', 'Secret AV ', 'SeriasLsRD', 'SignlSynRD', 'SirenSinRD', 'SlowFensRD', 'SlowtechNM', 'SphericlRD', 'SpnCycleRD', 'SquareFMRD', 'Sub6Rev AV', 'Sutra NM  ', 'SwellPadRD', 'Tarpit HS ', 'Thmn BC   ', 'TineBelsRD', 'TineLiteRD', 'TubeTek AV', 'Vernia RD ', 'Voltage M ', 'Vord RD   ', 'VriosPadRD', 'Warning NM', 'WarpCuspRD', 'WarpCuspRD', 'WastelndBC', 'Woofa RD  ', 'WowPad AV ', 'X-ModderRD', 'Xaris BC  ', 'Xianum BC ', 'XMorphLdXM', 'XMorphLpXM', 'Xraptor HS', 'YuckMouthM', 'YurayuraNM', '-INIT-    '
    ],
    'ROM-G': [
        '101-Sub RP', '2*Flute HS', '38 S@ws   ', 'Acidica HS', 'AllAges HS', 'Analog BC ', 'AnyMusicHS', 'aQire*F HS', 'aQire*M HS', 'Arpress HS', 'Auto 5ths@', 'AutobahnHS', 'Bamboo NM ', 'Be-Two RP ', 'BellLead @', 'BigShuflHS', 'Binbal HS ', 'Biosyn HS ', 'Boingy HS ', 'Bombers HS', 'BoxCutr HS', 'Br@ssWarm ', 'BsDX 20@8 ', 'Cadmium HS', 'Ceti HS   ', 'Clox HS   ', 'CurtisntHS', 'CutBrassHS', 'CuttaD6 HS', 'Cyber2 HS ', 'D50-50 HS ', 'DampPtchBC', 'DayDreamHS', 'Dgtalrido@', 'DigiBel1 @', 'DinoArp HS', 'DinoBassHS', 'Dis-Go HS ', 'Doyoyng HS', 'Dr.What?HS', 'Dworg HS  ', 'DX-File HS', 'EatPulseHS', 'Eferves HS', 'EkoRoad HS', 'Elemon HS ', 'ElfpianoHS', 'EmPyre HS ', 'eXtream RP', 'Fanfare @ ', 'FilmTrpsHS', 'FloBass BC', 'Frogger HS', 'Funk-U HS ', 'Gondor1 HS', 'Gondor2 HS', 'Gruvalimb@', 'HyperSus4@', 'ImpOsc02HS', 'Indus NM  ', 'IonFlux HS', 'J Halen MS', 'Kitchen HS', 'Knock-B HS', 'Latex 2 HS', 'Latinum HS', 'Laura @   ', 'LdGr@nForm', 'M@ndroid  ', 'MaxiMin HS', 'McDonna SV', 'Monolog BC', 'Movmnt2 HS', 'MowGrassHS', 'MWRingMdBC', 'NA Bass RP', 'NumanesqM@', 'NylSolo HS', 'Oby-Pad RP', 'Old Brs HS', 'Old S&H HS', 'Oscar1 HS ', 'p-g Chime@', 'P-Lead RP ', 'P6OO RP   ', 'Padings RP', 'PanDora HS', 'pd4Pe@ce  ', 'pd4YrPi@no', 'pdQuivery@', 'PerfectP@d', 'Phase 2 HS', 'PhatBrazBC', 'Pickles HS', 'PoIr@gNaOn', 'Polytix HS', 'PopL@yers ', 'PowerHuey@', 'Pro-12 RP ', 'ProFit HS ', 'Punctu8 BC', 'PurrBassHS', 'Raspry HS ', 'SFX-X~2RP ', 'ShineOn HS', 'Shortie BC', 'SlaplandHS', 'SoLead RP ', 'StarBeesHS', 'StarFallHS', 'Sugar1 HS ', 'Sugar5 HS ', 'Tack HS   ', 'TardisB HS', 'TibetianNM', 'Trancit HS', 'Trombic HS', 'TurnItOn @', 'TwinVox BC', 'UCantW@it ', 'V Dog BC  ', 'VelevateBC', 'Velo-Me RP', 'Vogue2 BC ', 'Vorwerk HS', 'Warbell HS', 'ZarndorfHS', '-INIT-    '
    ],
    'ROM-H': [
        '´,- CM"   ', '#-.- CM   ', '(-: CM    ', ')-^~ CM   ', '*~]=} CM  ', '--;=: CM  ', '60sSciFiHS', 'AftaglowPX', 'Alig M    ', 'Ambi@ns   ', 'Ambiano @ ', 'AmbienceBC', 'Anemone M ', 'AngstPadXM', 'AoilioA BC', 'AqutouchM@', 'AT FrqPdBC', 'BabyloneMS', 'BellfireBC', 'BlackHole@', 'BladeRun @', 'BubblX HS ', 'BukRogers@', 'Chant JS  ', 'ChaosBelHS', 'Crazike BC', 'Critter BC', 'CrossQ BC ', 'CrstlCave@', 'CrystalsMH', 'D=CM+1 HS ', 'DaBirds HS', 'Darkus PX ', 'DesolateBC', 'Dimril @  ', 'Dre@mGull ', 'DrownedP@d', 'EchoRain1@', 'Elevator M', 'Elohim HS ', 'EnoesqueJS', 'Etheral SV', 'Everest HS', 'eVolvyngM@', 'Explora M ', 'Fabrik SC ', 'FarOut M  ', 'FimbiantBC', 'FreqArp BC', 'Frozen JS ', 'Furrier BC', 'Ghost 2 JS', 'Ghoulie M ', 'GlasBirdHS', 'GlasGlisHS', 'H8000 FX @', 'Halo Pad @', 'HarmonixJS', 'HarmopadM@', 'Hell X @  ', 'Hoth M    ', 'Intim8 BC ', 'Iodine M  ', 'K@limbati ', 'Laquis BC ', 'LiquidSkyM', 'Lobster HS', 'McCloud HS', 'MeloDM XM ', 'Metalism @', 'MiamiP@d  ', 'Mistik SV ', 'MixChime @', 'MonolithJS', 'Moon PadJS', 'MoonriseHS', 'MySistarPX', 'Nebula M  ', 'Nowhere BC', 'Ocean BC  ', 'Outland JS', 'OutThereXM', 'P@dosphear', 'PB AlienXM', 'Petite BC ', 'Phantom M ', 'Phobos @  ', 'Plasma PX ', 'Pluto HS  ', 'PourDry HS', 'PyroFlowHS', 'RailingsBC', 'RichWind  ', 'RingDrone@', 'Ringjob BC', 'SempliceBC', 'SinBre@the', 'SinePad MS', 'SkyDeva @ ', 'SpaceP2 HS', 'SpaceVan M', 'Species HS', 'Squoid HS ', 'SteamWavBC', 'SunChildHS', 'TangerineM', 'Terror3D @', 'TheWell JL', 'Tribbles @', 'ulTIma BC ', 'Umena BC  ', 'Unusual SV', 'Ursula M  ', 'Valium M  ', 'VCSwolf HS', 'VelocrysBC', 'Vlhurgs HS', 'WarmWavsBC', 'Warper @  ', 'Wave-PadJS', 'WavePad BC', 'Westwego M', 'Whales JS ', 'WhoPad BC ', 'WndChimeHS', 'Yaquis BC ', 'Zimoux BC ', '-INIT-    '
    ],
    'ROM-I': [
        'AllRoundXM', 'AnaBass BC', 'AnArp BC  ', 'ArdeKey M ', 'ArpIn7 @  ', 'Asfo NM   ', 'Atlantis M', 'AutoKit BC', 'B-SquareBC', 'BasemineHS', 'Bass!!! CC', 'Beaker M  ', 'BeniBeniBC', 'BombTraxMS', 'Boppin´ SV', 'Brawndo MH', 'BsBowzr07@', 'bsXexxor @', 'ButtrflyMS', 'CellStabBC', 'ClubbingMS', 'CXish MH  ', 'DaydreamMS', 'DCLead CC ', 'Degrade AV', 'DreamnPdBB', 'Drop FX PS', 'DrunksawSV', 'DryDie AV ', 'Dst3o2 BB ', 'DuckDivrHS', 'EatBass MH', 'Electro AV', 'EuroSubBMS', 'FatFunk2MH', 'Flyin´ SV ', 'FlyingT CS', 'FogHat M  ', 'Frippz MH ', 'Goatic SV ', 'Grog PN   ', 'H2SO4 @   ', 'HaloklinMH', 'HardOne HS', 'Hifive SV ', 'HihatRunMS', 'HollowBsPS', 'HrdshellNM', 'HyperLd QR', 'HyperSqrMS', 'HyperSus4@', 'Iller MH  ', 'Impact MS ', 'In spaceSV', 'IntntentSV', 'KoolSawsMS', 'Korsant AV', 'Life NM   ', 'LktroPlkBC', 'Lofibrk NM', 'Lush MH   ', 'Massive XM', 'Minion M  ', 'MotoSyncMS', 'MPScreamBC', 'MstrBrn SV', 'NewGBassBC', 'NewVoV4 BC', 'NineTrem @', 'NinthHvnSV', 'Nitrous BC', 'NoiseArpMH', 'NoseDiveBC', 'NuNrg MS  ', 'OddgssaySV', 'OktaviusMS', 'Oldboyz BC', 'OldSkul AV', 'OrchBlstMS', 'Pacific M ', 'Ph@zPlk@08', 'Phazzah HS', 'Plugga @  ', 'PowerPadMS', 'Psycho MH ', 'PunchBssMS', 'PuristicMS', 'Ravin´ BC ', 'RawBass MH', 'Re-Flex MS', 'RelativeMS', 'RePunch MS', 'Rhenium QR', 'RingThngBC', 'Ripper MH ', 'SciFiChrMS', 'ScratchyPS', 'SineDiveBC', 'SlowSilkMS', 'SlowtechNM', 'SoftBassMS', 'Softie MS ', 'SolidGoaMS', 'SqrBass XM', 'SuprNovaMS', 'SweetSqrXM', 'Sync303 MS', 'Synthoni@ ', 'Take OffPS', 'Tech1 BB  ', 'Thr3sum BC', 'TIBuzzerMS', 'TightBs AV', 'TimbArp BC', 'TinyBee HS', 'TooMnyBlz@', 'Tracker MS', 'Transas CC', 'TubeTek AV', 'UK´Bass MS', 'UniVoV BC ', 'Veldisa BC', 'Voltage2MS', 'Warmer AV ', 'Wendy+ HS ', 'WhatThe.MS', 'X-FlangeMS', '-INIT-    '
    ],
    'ROM-J': [
        'AcidArp M ', 'AcidRain M', 'AhaaDistJL', 'Beano M   ', 'Bhurly M  ', 'Booberry M', 'Bullfrog M', 'C*nted M  ', 'CashCrop M', 'ClikClak M', 'Clockers M', 'ClosedHatM', 'ComeDown M', 'DaClap M  ', 'Dayz M    ', 'Diana M   ', 'DieSoon M ', 'DigDoug M ', 'Dirty L jh', 'DoubleD M ', 'DubTest M ', 'DuckFeet M', 'Dumbo M   ', 'Eastside M', 'Fatass! M ', 'Felcher M ', 'FelxDmstJL', 'Fonkah M  ', 'Foursome M', 'FunkNastyM', 'FunkOff M ', 'Furley M  ', 'Gachet M  ', 'Gamera M  ', 'Ganja M   ', 'GasHuffa M', 'Gateman M ', 'GoatRock M', 'GoFigure M', 'GrapeApe M', 'Hesher M  ', 'Horror2 jh', 'HotKarl M ', 'Hydra M   ', 'Icarus M  ', 'Industry M', 'Jaco M    ', 'Jahmekya M', 'JizzMop M ', 'Junkie M  ', 'KoolFM M  ', 'Kuster M  ', 'Lando M   ', 'LastFix M ', 'Leary M   ', 'Lezzie M  ', 'Lisbon M  ', 'Loner M   ', 'Lycra M   ', 'MadhattanM', 'Majesty M ', 'Malfunk M ', 'Manga M   ', 'Mentor M  ', 'Mercury M ', 'Midnite M ', 'Monkfish M', 'Monsta jh ', 'Monument M', 'Moonie M  ', 'Mosquito M', 'Mothra M  ', 'Move M    ', 'Napalm M  ', 'NewYork M ', 'NextKin M ', 'NO2Head M ', 'NotNice jh', 'OpenHat M ', 'PadThai M ', 'Payback M ', 'Petrol M  ', 'PorkPie M ', 'Pulsine M ', 'Python M  ', 'Quazar M  ', 'Rasberry M', 'RatSync M ', 'RedAlert M', 'Reminise M', 'Resin M   ', 'Rezonard M', 'Roaches M ', 'Rodan M   ', 'RumpRoastM', 'Scanners M', 'Seagull M ', 'SheMale M ', 'Simplex M ', 'SinisterJL', 'SkiMask M ', 'Skylab M  ', 'Slayer M  ', 'Socrates M', 'Sparta M  ', 'Spaz M    ', 'Sqash M   ', 'SqrSwlw JL', 'Tasm1 M   ', 'Tasm2 M   ', 'Tasm3 M   ', 'TechKey1 M', 'TechKey2 M', 'TheDawn JL', 'Timbuktu M', 'Traffic M ', 'TwinPeaksM', 'Undertoe M', 'Uranium M ', 'ViceM     ', 'Vindaloo M', 'Visitor M ', 'Wombat M  ', 'Woooow AV ', 'Wormzer M ', 'Xanax M   ', 'Zest M    ', 'Zulu M    '
    ],
    'ROM-K': [
        '68-CreakHS', 'Arctis HS ', 'AT-Mini HS', 'AwashBs HS', 'B-Kewl SV ', 'Backing HS', 'BadTape HS', 'Baryon HS ', 'Begin? HS ', 'BerimTamHS', 'Borgano SV', 'BowBouncHS', 'Bronze HS ', 'CantburyHS', 'ClubMed HS', 'Congoid HS', 'CptKork HS', 'DaChurchSV', 'DancePn HS', 'Dangelo HS', 'DarkTombSV', 'DB-Goer HS', 'Dirtron HS', 'Dread-0 HS', 'Dublyoo HS', 'Dynette HS', 'E.Rigby HS', 'Easter1 HS', 'Expense HS', 'Flam&Co HS', 'Flats HS  ', 'Flutes HS ', 'Froese HS ', 'FunctionHS', 'Ganges HS ', 'GlasStrgSV', 'Gliss2 HS ', 'Goomby HS ', 'Goudam HS ', 'Handsaw HS', 'Hektik HS ', 'HillAgesHS', 'HissPad BC', 'J.Edgar HS', 'Jawdan HS ', 'JazRoad HS', 'Jester HS ', 'JuicOrg HS', 'Latex HS  ', 'Macho HS  ', 'Mandoid HS', 'Manfman HS', 'MarsAtx HS', 'Meddle HS ', 'MelloVl HS', 'MinorityHS', 'Monza HS  ', 'MoonWeedHS', 'Multasm HS', 'MW-StepsHS', 'Nanites HS', 'Needles HS', 'NewStrumHS', 'Nocoder HS', 'Oboe HS   ', 'Oddigy HS ', 'Oh Bee SV ', 'Orange HS ', 'Outpost HS', 'Pac-it SV ', 'PanShakeHS', 'Picking HS', 'PingOrg HS', 'Pizza HS  ', 'PlukalogHS', 'PopCorn HS', 'Prions HS ', 'Pstyro3 HS', 'PsychordSV', 'Pumpah HS ', 'PutzFrauHS', 'Qatsi HS  ', 'Quack! HS ', 'RadioG HS ', 'Raw Saw SV', 'Saloon HS ', 'Saxpet HS ', 'ScrapyrdHS', 'Series3 HS', 'SirNevilHS', 'Sitar2 HS ', 'Skrape HS ', 'SlaplandHS', 'Slapska HS', 'SleigherHS', 'SpacePadSV', 'Spring HS ', 'Spy HS    ', 'Squeeze HS', 'Sugar2 HS ', 'Sunder HS ', 'Tabloid HS', 'TankYou HS', 'TheDome HS', 'Thustra HS', 'TimeStepHS', 'TI|LinerSV', 'Torque HS ', 'TownshipHS', 'Trancit HS', 'TranQ SV  ', 'TrebleB HS', 'TrebleB HS', 'Trumps HS ', 'Tunnel HS ', 'TweakMe HS', 'TwoOfUs HS', 'UnstableHS', 'Untune HS ', 'Vanilla HS', 'Voodoo HS ', 'Warlord HS', 'Wheee! HS ', 'WishBom HS', 'WoodyBs HS', 'X-Didge HS', 'X-Werx HS ', 'Zorch HS  '
    ],
    'ROM-L': [
        'S-1973 @  ', 'x(o-o)x @ ', '100 tinoPX', '3001 SO PX', '4Gr@ins-Dy', '5th heroPX', 'AerSyn @  ', 'Aeternal @', 'Alloy HS  ', 'Ambiont PX', 'AmrCnBe@uT', 'AngelianPX', 'Angels SV ', 'AprilPad@ ', 'Aqua PX   ', 'Arigato PX', 'Armus SV  ', 'Astr@     ', 'BellsickPX', 'Belly PX  ', 'Blongo HS ', 'BluePl@ne2', 'Callist@  ', 'CanHappen@', 'CeuAzul PX', 'ChoBell jh', 'Clocks PX ', 'CommonTon@', 'CybrlifeSV', 'DarkmoonSV', 'DayGool@s ', 'DelayLama@', 'DigiBel2 @', 'DigiBel3 @', 'DigiBel4 @', 'DigmahalPX', 'DlithiumHS', 'Dragons @ ', 'Dreams PX ', 'DriftingPX', 'EeriebedSV', 'EPW@sh    ', 'Feather PX', 'FibogldePX', 'Flangepad@', 'Floater PX', 'Foogpad2P@', 'Gently 2 @', 'Glassy PX ', 'GlstowerSV', 'Harpa PX  ', 'Heroes @  ', 'Hi&Good PX', 'HiEther HS', 'Horizon PX', 'Industron@', 'Jovi@n    ', 'Junky@rd  ', 'LayerHold@', 'LFO2phs PX', 'LikeSkin @', 'LiquiP@d  ', 'LoEther HS', 'Lun@rTide ', 'LunarArp @', 'Luv (at)PX', 'M@ Olympus', 'Mares PX  ', 'Melted PX ', 'MingettiSV', 'Minus80 PX', 'Mr.Kite @ ', 'MusicBoxPX', 'Mutagen@  ', 'Neon PX   ', 'NeoworldSV', 'Nerves @  ', 'Neutron@  ', 'NevrmindPX', 'Newb PX   ', 'Noias PX  ', 'Orion PX  ', 'Ovatone HS', 'PatiencPd@', 'Paz PX    ', 'PearlpadSV', 'Phage HS  ', 'Pl@net:1  ', 'Pl@net:8  ', 'Pod PX    ', 'PoleNoise@', 'PsilobudPX', 'Psyght PX ', 'QT-Soft RP', 'Quivery @ ', 'Reaktor PX', 'reSINance@', 'Reson@tion', 'Reternal@ ', 'ReZombies@', 'Ride it PX', 'S@nctuary ', 'Sadings RP', 'Sci-Vi @  ', 'Shiny SV  ', 'SineLang @', 'Sinus9 XM ', 'Softie PX ', 'Sol@rize  ', 'Sono PX   ', 'SpaceFX PX', 'SpaceOrkHS', 'Spiritu @ ', 'Sun&TreePX', 'SundromeHS', 'SupershyPX', 'Susto PX  ', 'SweetO2 @ ', 'Syl@rsMind', 'Terraform@', 'TimefluxSV', 'TortrPadBC', 'TrippyPad@', 'TStationPX', 'Up&Down PX', 'Venusian @', 'W@iverie  ', 'W@ve2.3   '
    ],
    'ROM-M': [
        '2030SawzSV', '64Degee MS', 'A.Pop MS  ', 'AcidChrdMS', 'Adagio MS ', 'AirTonicMS', 'AlphA SV  ', 'AmbulantMS', 'Analand SV', 'Anubis MS ', 'BasStar jh', 'BigBeat MS', 'BigPhaseMS', 'BittBassMS', 'Bomber MS ', 'Brasso MS ', 'ButtrflyMS', 'ByZero MS', 'C cup SV  ', 'C-Love SV ', 'C-Rave SV ', 'C-Trek SV ', 'Chapel MS ', 'CharactrMS', 'CoderArpMS', 'CoderPadMS', 'Commers2SV', 'CoolChrdMS', 'CreamPikMS', 'CrysalisMS', 'Cubus MS  ', 'CultOrgnMS', 'D-Phunk MS', 'D50Lead MS', 'DancnldySV', 'DarksideMS', 'Deepest SV', 'DeepWeepMS', 'DirtBox MS', 'DistPickMS', 'DromeCrdMS', 'DuskwoodMS', 'E-Lead MS ', 'Fishy C SV', 'FizzBizzMS', 'Flutex MS ', 'Flutex2 MS', 'FM BoostMS', 'ForgivenMS', 'FrancaisSV', 'Freaks MS ', 'Frogger MS', 'FunkBassMS', 'FutureMgSV', 'Gamelan MS', 'GianaArpMS', 'Go Rave!MS', 'Goatic 3SV', 'Halo MS   ', 'HappyVoxMS', 'HarakiriMS', 'Haunted MS', 'HihatRunMS', 'Holland MS', 'Horror! MS', 'HyperSawMS', 'HyperSqrMS', 'I-saw-aCSV', 'Jessel MS ', 'Ligaya MS ', 'Linear MS ', 'LoFi SawMS', 'LoFi-WhaMS', 'Lovly80sMS', 'MantorokSV', 'MatricesSV', 'MayaFireMS', 'Megane MS ', 'Mettler MS', 'MinitrnsSV', 'MnstrSawMS', 'MnstrSw2MS', 'MotoSyncMS', 'MovinPadMS', 'MutePickMS', 'NarcoticMS', 'Neurons SV', 'Noomed MS ', 'Noomed2 MS', 'noToy MS  ', 'NuNrg MS  ', 'OberBrssMS', 'OktaviusMS', 'OrchBlstMS', 'PhoneSqrMS', 'PhonoboyMS', 'PsyBat MS ', 'PulvrTrmMS', 'PuristicMS', 'Q-Games jh', 'RavinmadSV', 'RelativeMS', 'RePunch MS', 'SadSaws MS', 'Saw You MS', 'Schilla MS', 'Sharp MS  ', 'Sick SQ MS', 'SlowSilkMS', 'SoftBassMS', 'SpheroidMS', 'Stack X MS', 'SunPianoMS', 'SupaCoreMS', 'SuperWrmMS', 'TechnoidSV', 'Theory MS ', 'TiberiumMS', 'TIBuzzerMS', 'TinytrncSV', 'Tracker MS', 'UpliftFXMS', 'Vogue MS  ', 'Wind MS   ', 'Wurly MS  ', 'XylotronMS', 'Zapper MS ', 'Zeepad SV '
    ],
    'ROM-N': [
        'AutoBendBC', 'An@gry    ', 'Avenues JS', 'B-SquareBC', 'Back280sSV', 'Base MH   ', 'BC NewVoV3', 'BellAir MH', 'BlkvelvtSV', 'BusysawsSV', 'ChilloutJS', 'ChoralisSV', 'ChrunchyJS', 'ClubbassSV', 'ClubtoolBC', 'Comm basSV', 'Contra BC ', 'CosmicbsSV', 'CreameryBC', 'Cyclone JS', 'D&B FX    ', 'D&B Geneqa', 'D&B Woover', 'Da Funk BC', 'Dawn JS   ', 'Decay JS  ', 'Deep9thsBC', 'Devlish SV', 'DHR Amb BC', 'Digedi JS ', 'Driver SV ', 'Drmswpr SV', 'Duffer BC ', 'Far EastJS', 'FatWah BC ', 'Five in1BC', 'FlyBy BC  ', 'FnkNastyBC', 'Fripper JS', 'Future XSV', 'FuturwldSV', 'GarBass8BC', 'Girls SV  ', 'Glassey SV', 'Goatic SV ', 'GoindownSV', 'GoodniteJS', 'Hifive SV ', 'HOA Pad SV', 'Hollow JS ', 'HongKongBC', 'Hoppin´ SV', 'IndiArp BC', 'IntntentSV', 'Jazzy JS  ', 'JoeZolo BC', 'KatmanduJS', 'KingsizeJS', 'LatitudeSV', 'Let´s goSV', 'Lite JS   ', 'LongskrtSV', 'Maja JS   ', 'Mamba JS  ', 'MentalitJS', 'MetalsynJS', 'Move it SV', 'MoveMyMWBC', 'Muzzle BC ', 'NasalbasSV', 'NewVoV4 BC', 'NoiztoyzJS', 'OctvHoprBC', 'OddgssaySV', 'OffSoft BC', 'OffTopicHS', 'Oil-crwlSV', 'Pad ´77   ', 'PadAlertMH', 'Pathos BC ', 'Pensive BC', 'Phlute JS ', 'Pitchy BC ', 'PizzachiSV', 'PlaycoolSV', 'PlugAsiaMH', 'Plugged JS', 'Polar JS  ', 'PolyGrovJS', 'PseudoTBSV', 'Pulsar SV ', 'Q-Pad BC  ', 'RbbrHrp2BC', 'Red lineSV', 'RepeaterJS', 'RestlessBC', 'Rezoid SV ', 'Rezzer2 BC', 'Rise up!SV', 'Ritchie SV', 'RubbrHrpBC', 'S&HOrganBC', 'Sawz2 SV  ', 'Sharp BC  ', 'Sickly BC ', 'SilkArp SV', 'SinebassJS', 'SomethngSV', 'SpitfireJS', 'Spoiled SV', 'Spring SV ', 'SpringPdSV', 'Squink HS ', 'StellarpSV', 'StickyPdBC', 'SubmergeSV', 'SwingArpPS', 'T Pot BC  ', 'T-Axxe JS ', 'TenInchJS', 'ThirdEarJS', 'Tinycat SV', 'TiptaptuSV', 'TwotonesBC', 'UniVoV BC ', 'V-Bells JS', 'Vapour SV ', 'VindictrSV'
    ],
    'ROM-O': [
        '%SOFT% CC ', '2 LFO 2 CC', '2-Burst RP', '2-Chord RP', '7thCord RP', '80s RP    ', '=BASS= RP ', 'A FreeK CC', 'Alamos CC ', 'AlfBass RP', 'AmiGito CC', 'B-Boys CC ', 'BandPad RP', 'Bandrun CC', 'Bass Me RP', 'BeautySyn@', 'BigBass2CC', 'BPMPad RP ', 'BsBuster @', 'C4Phone CC', 'Chord-U RP', 'ChrysPadSV', 'Cinema1 CC', 'Cinema2 CC', 'Club-To RP', 'Cord-1 RP ', 'D50MorphCC', 'Dancer @  ', 'DeeBass RP', 'DiganOB CC', 'Diosa CC  ', 'DSP-V RP  ', 'DubChrdsM@', 'DukaliopCC', 'Duke5CC   ', 'DX ThickCC', 'Early80sMH', 'EarthLd CC', 'Ease RP   ', 'Entropy MH', 'EP Res @  ', 'EP3DogNyt@', 'Falling1CC', 'FanKWrldCC', 'FenderB RP', 'Filters RP', 'Fiona MH  ', 'Flower CC ', 'Fm&Mod CC ', 'Garfisa CC', 'Genssis CC', 'GoBass RP ', 'Hancock CC', 'Hawsch RP ', 'Hohner CC ', 'IQsnare RP', 'JDLead CC ', 'JoeZ Vc CC', 'Joni M. CC', 'JPEight PS', 'K-Organ RP', 'LAVirginCC', 'Lullaby CC', 'MadrePadCC', 'MAXWave RP', 'Mellotr.RP', 'Mercado CC', 'MeShell2CC', 'MgBass1 CC', 'MgStereoCC', 'Mistery RP', 'MO-TJO RP ', 'Moderno CC', 'Montero CC', 'MooBass RP', 'Mover RP  ', 'MS-10 2 RP', 'MS-99 RP  ', 'NoiseAA RP', 'Not-Pad#RP', 'O-ME-2 RP ', 'OBeeBee CC', 'OBrass CC ', 'Open P5 CC', 'OrganDigi@', 'OuBeeStrCC', 'Oz-Lead RP', 'Pad-Flg RP', 'People1 CC', 'Phasa RP  ', 'PolyPha RP', 'ProlesLog@', 'Q-Teck RP ', 'RoboPad RP', 'SH-123 RP ', 'Sorry RP  ', 'SQRSolo CC', 'StpSeqMe!@', 'Str-Arp RP', 'STR-II RP ', 'Str-WoW RP', 'StrAlterCC', 'Strings RP', 'T-8 RP    ', 'T-Dream RP', 'TD-Seq RP ', 'TE-T42 RP ', 'Tec-Str RP', 'The-BD2 RP', 'Ting RP   ', 'TomBass RP', 'Upwards @ ', 'Varpeg RP ', 'VeloPEW RP', 'Vi-Rtro RP', 'Vichord RP', 'Vitar RP  ', 'Vo-Pad RP ', 'VR-78 1 RP', 'VR-78 2 RP', 'WaveSeq CC', 'Windo RP  ', 'X Mean RP ', 'X-Mover HS', 'X0X Kck RP', 'XXI CC    ', 'Z-Keys SV ', 'Zen CC    '
    ],
    'ROM-P': [
        '7thHeavnJS', 'Ah Reso JS', 'Anabo|icJS', 'Anima JS  ', 'Animate JS', 'ArtificlJS', 'Bad S JS  ', 'Bassic JS ', 'Bassta JS ', 'BasstardJS', 'BC VoV-2BC', 'BC VoV-3BC', 'Beatbox JS', 'Bella JS  ', 'Bella 2 JS', 'BellaArpJS', 'Big Fly JS', 'Birdy JS  ', 'Braxter JV', 'CalliopeJS', 'Carpets JS', 'ChainsawJS', 'Choir 4 BC', 'Cold SawJS', 'ConcreteJS', 'Crispy2 jh', 'Cydonia1XM', 'Deeper JS ', 'Dig Me JS ', 'Dig ThisJS', 'Disco OK  ', 'Donkey JS ', 'DreBeat jh', 'Dukbass+BC', 'Dysonia BC', 'EnglArp JS', 'FeedyPadJS', 'Feng JuiJS', 'FM Bass JS', 'FM Sequ jh', 'For DeepJS', 'FuzzBellJS', 'Fuzzbox JS', 'FX Drum JS', 'GinaPad JS', 'Glitch OK ', 'Goa4 it JS', 'Guitar4 jh', 'HackbartJS', 'Hauntin´JS', 'Hovis JS  ', 'Hybrid JS ', 'Impact MS ', 'Induced JS', 'InfectedJS', 'InfinityJS', 'JaySync JS', 'JunoApg JS', 'Justice JS', 'KonKilr@  ', 'KyotoLd JS', 'Laville JS', 'Lead JS   ', 'LFantSqid@', 'LFOmove jh', 'LoFine jh ', 'M@inTheBox', 'Majman @  ', 'MajorityJS', 'Mallet JS ', 'Mamamia jh', 'Marbles CC', 'Melter XM ', 'MorsSpc JS', 'Moving JS ', 'Nasty JS  ', 'NiceArp JS', 'No Age JS ', 'Odyssey JS', 'OldScol OK', 'Opener JS ', 'Organic JS', 'OverloadJS', 'OvertoneJS', 'Percold JS', 'Piggy JS  ', 'PluckMe BC', 'PolySin JS', 'Prodigy JS', 'Puls4thsBC', 'Pulsic JV ', 'Puncher JS', 'Q-Lead jh ', 'Quarx JS  ', 'Random JS ', 'Raw JS    ', 'Rhy-Arp JS', 'Rough JS  ', 'ScanJob JS', 'Scary jh  ', 'SeqIt JS  ', 'Sim SalaJS', 'Simply JS ', 'SinderelJS', 'ineBeezJS ', 'SmoothBsBC', 'Soaker JS ', 'Soft3rdsBC', 'Soloist JS', 'Start UpJS', 'Subaqua BC', 'Sweeper JS', 'Taurus JS ', 'Tight JS  ', 'Tubez JS  ', 'Tubular JS', 'Uprite JS ', 'V-Birth1 K', 'Vienna JS ', 'Virus B JS', 'Voyager JS', 'Wailin JS ', 'WalkaArpJS', 'Walker JS ', 'Waver JS  ', 'WeeBell jh', 'Whirly JS ', 'X-Bellz JS'
    ],
    'ROM-Q': [
        'GO ON! MS ', 'Lonely MS ', 'N-R-G! MS ', 'Photex MS ', '1 FingerMS', '303Sync MS', 'AftrglowMS', 'Alert!! MS', 'AlroundrMS', 'AmbienceMS', 'AmbrStngMS', 'Angels MS ', 'Binary MS ', 'BombTraxMS', 'BPMover PS', 'BubblizeMS', 'Cabinet MS', 'Careful!MS', 'CataclsmMS', 'CavePizzMS', 'ChainSawMS', 'ChilloutMS', 'ChinaToyMS', 'ChordMe MS', 'Circles MS', 'ClubbingMS', 'ClubSub MS', 'CoolBlipMS', 'Crazy!!!MS', 'CrystalsMS', 'DarksideMS', 'DaydreamMS', 'DialFFM MS', 'DropzoneMS', 'DryLand MS', 'DscotheqMS', 'E-motionMS', 'EuroBassMS', 'EuroSaw MS', 'EuroSaw2MS', 'EuroStngMS', 'EuroSubBMS', 'FatMoogyMS', 'FiltopiaMS', 'FlngomatMS', 'Fltopia2MS', 'Fltopia3MS', 'FM Bass MS', 'FMShaperMS', 'GrgorianMS', 'HackBassMS', 'Hazard MS ', 'Heaven MS ', 'Hoboken MS', 'HolywoodMS', 'IceDartsMS', 'InfinityMS', 'JP Bass MS', 'KemistryMS', 'KoolSawsMS', 'KraftLd MS', 'KraftLd2MS', 'KrftworxMS', 'LdStrngzMS', 'LoFiVibeMS', 'LostInT.MS', 'Maniac! MS', 'MegaFuzzMS', 'MegaraveMS', 'MegaWattMS', 'ModMnstrMS', 'OffbtDblMS', 'OffshoreMS', 'OldSkoolMS', 'ParadiseMS', 'PartyOn!MS', 'Plastic MS', 'PowerPadMS', 'Public MS ', 'Pulsar MS ', 'PulsArp MS', 'PunchBssMS', 'PWFatty MS', 'PwrStackMS', 'R-Whip MS ', 'RaverLneMS', 'RawBlineMS', 'RckDaClbMS', 'Re-Flex MS', 'Rising MS ', 'Rvltn303MS', 'SciFiChrMS', 'Smoothy MS', 'Snapper MS', 'Softie MS ', 'SolidGoaMS', 'Spacy303MS', 'SpceBrasMS', 'SpceDustMS', 'SquarDncMS', 'StrburstMS', 'SuprNovaMS', 'SyncStarMS', 'Tachyon MS', 'TekStepzMS', 'TranceFXMS', 'Tri-AnglMS', 'TriShaprMS', 'TrncTipsMS', 'TrnsfrmrMS', 'TubeDstxMS', 'Typhoon MS', 'Typhoon2MS', 'Typhoon3MS', 'U-Punk MS ', 'UK´Bass MS', 'UniBass MS', 'V...ger MS', 'Vintage MS', 'VocodrPdMS', 'VowelSwpMH', 'WaveridrMS', 'WhatThe.MS', 'Wicked MS ', 'Wraith MS ', 'Wraith2 MS', 'X-FlangeMS', '{TheOne}MS'
    ],
    'ROM-R': [
        '8BitHellXM', 'AcidLineXM', 'Amoeba M  ', 'AngelDustM', 'BadAcid M ', 'Bass 87 XM', 'BD 3-4 XM ', 'Bella M   ', 'BirdFlu M ', 'BitchTitsM', 'Bombast jh', 'Bonesnap M', 'BP Pad XM ', 'BPGrooveXM', 'BpHpOsc XM', 'Broken M  ', 'Chappele M', 'CheezMasXM', 'Cockring M', 'Cydonia2XM', 'DaBrain jh', 'DaftFunk M', 'December M', 'DeepAb XM ', 'Diablo M  ', 'DigiScrmXM', 'Dirtweed M', 'DirtyDeedM', 'DistArp1XM', 'DistArp2XM', 'DistLd1 XM', 'DistLd2 XM', 'DistRez XM', 'DrunkET XM', 'DrunkSpcXM', 'EBM Ld2 XM', 'Edamame M ', 'EvilDeadXM', 'EvilLeadXM', 'Feeder XM ', 'Fellacio M', 'FutureBsXM', 'FuturEP XM', 'GlassJoe M', 'GoGrooveXM', 'Goulash M ', 'GravelPitM', 'Groov7thXM', 'GutterHo M', 'HardHousXM', 'Hazzard M ', 'Hellcat M ', 'Hideous M ', 'HighTimesM', 'HollaBackM', 'HP Bass XM', 'Hypnosex M', 'Insulin M ', 'Intense XM', 'Invader M ', 'IOC BassXM', 'Kismet M  ', 'Kligon M  ', 'Kompakt M ', 'Kramer M  ', 'Lizard M  ', 'LoTatar jh', 'Lurker M  ', 'MadLFO XM ', 'Magilla M ', 'Mastadon M', 'Mellow XM ', 'MelodiBzXM', 'MelodiTWXM', 'MeltArp1XM', 'MeltArp2XM', 'MeltBassXM', 'MeltGrv XM', 'MoonArp XM', 'Moroder M ', 'Mythical M', 'New IOC XM', 'Nosberry M', 'Nostrils M', 'NuSkool jh', 'Nutria M  ', 'OffBass XM', 'Oleander M', 'Orca M    ', 'Oscar M   ', 'OscilateXM', 'Overdose M', 'PacemakerM', 'PhaseLd XM', 'PlainBasXM', 'Plisken M ', 'Potato M  ', 'RatPack jh', 'RebelBassM', 'ResoMeloXM', 'RezArp XM ', 'Rezoland M', 'RezStrngXM', 'Rizla M   ', 'Rubik M   ', 'S9 Loop XM', 'Saigon M  ', 'SawComm XM', 'Seka M    ', 'SexTape M ', 'ShalloBsXM', 'Sneaky M  ', 'SpellcastM', 'Splenda M ', 'Stranger M', 'SuckaFreeM', 'Talker XM ', 'Tardo M   ', 'ThinkPinkM', 'Tipsy M   ', 'Titties M ', 'Torque M  ', 'TranzArpXM', 'Tubby M   ', 'UndawrldXM', 'Useless M ', 'WarMongerM', 'Xzanbar M '
    ],
    'ROM-S': [
        '!U"! CC"  ', 'ADN CC    ', 'AllRoundXM', 'ArpSwingPS', 'BallenasCC', 'Benny B JL', 'BigArp CC ', 'BudapestCC', 'CheezArpXM', 'CheezLd XM', 'Chord ! PS', 'Ciko CC   ', 'Circus CC ', 'ComeOne XM', 'ComMan JL ', 'Detuner XM', 'Dizzy JL  ', 'DuHast XM ', 'DubBass jh', 'DX 100 CC ', 'EBM Ld1 XM', 'Elastic JL', 'Error XM  ', 'Eyyy CC   ', 'FakeGtr JL', 'Feeder JL ', 'FM Perc CC', 'FM&MOD2 CC', 'FM)MW CC  ', 'FreakMinCC', 'Gargara CC', 'Gimme5 JL ', 'Grose JL  ', 'Guitar JL ', 'Heaven JL ', 'Hoedown JL', 'HongKongCC', 'HonkHonkJL', 'Horny JL  ', 'Horror JL ', 'HP SauceJL', 'ImFrenchJL', 'IOCBass1XM', 'JeanLeadXM', 'JMJ Arp XM', 'Juho L´sJL', 'KarnEvl JL', 'KeratArpCC', 'Killers XM', 'LamaLeadCC', 'MamasGunCC', 'MapaCC    ', 'Mayhem XM ', 'MeltIntrXM', 'MINI-M++CC', 'MiniExp CC', 'Moogish JL', 'MoonBassXM', 'MoonLeadXM', 'MorpheusJL', 'MS HammrCC', 'Mth Sky CC', 'MW SeqG CC', 'Mystic JL ', 'N N 1 CC  ', 'NewLeadQCC', 'NiceBassJL', 'Ninty JL  ', 'NitzerBsXM', 'Nokia JL  ', 'NotPad2 JL', 'NuWaveLdCC', 'O Pitch CC', 'O Pitch2CC', 'OB 10 CC  ', 'OB Neee CC', 'OB Tero CC', 'OffLoop XM', 'Ol´SkoolXM', 'OldLead jh', 'Osc3 CC   ', 'Pad S&H CC', 'PeacePd CC', 'People2 CC', 'PhaseMW CC', 'PhasEns CC', 'Plux0r SV ', 'PPG TI jh ', 'PPGCruelCC', 'Remark CC ', 'Rosario CC', 'S&HSeq2 CC', 'S9Groov2XM', 'SawArp XM ', 'Scared CC ', 'SeqAlienCC', 'ShoutLd XM', 'Simul8r XM', 'SineBudaCC', 'SpaceLabXM', 'Spain2 CC ', 'Stagga SV ', 'StrAbejaCC', 'SubBass CC', 'SubBass XM', 'Sweep CC  ', 'SweepichCC', 'SweetSqrXM', 'SynthPopXM', 'TalkPad CC', 'ThickSawJL', 'Trilogy JL', 'UFO 33 CC ', 'UMBbass CC', 'VeryFar CC', 'Vi-bass+CC', 'WaitingRCC', 'Wakeman CC', 'WakMoogyCC', 'WavetronCC', 'WetSqrBsXM', 'Zooz SV   ', 'AtalashiSV', 'LFOverkil@', 'Hammono @ ', 'StpSeqMe!@', 'Chor@leSin', 'Form@ndyhd'
    ],
    'ROM-T': [
        'AESound zs', 'AldoNovaM ', 'AmbientBlJ', 'AmbientFXJ', 'ambiRgM zs', 'AnHigh M  ', 'Arcade BC ', 'Atlas J   ', 'Attack! J ', 'AutoTknoBC', 'B-Deep M  ', 'B-Foe M   ', 'BadLand M ', 'BassIk M  ', 'basting zs', 'basting2zs', 'bigTung zs', 'Bleu! M   ', 'Blotto M  ', 'Bubble2 M ', 'CappSt M  ', 'Cavsak M  ', 'cirqStb zs', 'CLEeeN M  ', 'Cloakin M ', 'cutRes zs ', 'decDATA1zs', 'decDATA2zs', 'decDATA3zs', 'deciDAT4zs', 'dirty zs  ', 'Donky BC  ', 'dopeEp zs ', 'Dragon M  ', 'dropIT zs ', 'drpBomb zs', 'Drubber BC', 'Dry Bass J', 'dstStep zs', 'Dubsak M  ', 'Dumb! M   ', 'Empira 2M ', 'Entropie J', 'Everest J ', 'Facial M  ', 'FePudn zs ', 'FlutDrumBC', 'fnkStrg zs', 'GBEp3 zs  ', 'george2 zs', 'GooHat M  ', 'GotHAM! M ', 'HIDEson M ', 'HiWaves jh', 'IndustryBC', 'LepY2 zs  ', 'LepY3 zs  ', 'lootRng zs', 'Lost M    ', 'LowBass jh', 'marimba4zs', 'MeBad? M  ', 'Menace M  ', 'MONose zs ', 'mostHih zs', 'Mr.Big jh ', 'Mr.Foo M  ', 'Necro M   ', 'NoFuture M', 'orguit zs ', 'Plead M   ', 'PowerStrnJ', 'pulsRay zs', 'Quarp BC  ', 'RbbrBellBC', 'ReBird M  ', 'resPad zs ', 'Reverse J ', 'rmBack zs ', 'rngPort zs', 'Roboe zs  ', 'RuffLea.jh', 'ShineChrdJ', 'shivrPd zs', 'sineZZZ zs', 'sinMorf zs', 'sitar zs  ', 'Skware zs ', 'smoovLd zs', 'SoftBell J', 'Softi J   ', 'SoftSeq. J', 'sofueMODzs', 'SoSad M   ', 'SpaceNighJ', 'Spinner M ', 'spoolPd zs', 'sqPadMM zs', 'squar00 zs', 'Sr.Goo M  ', 'step2it zs', 'Subbass zs', 'Sunday M  ', 'Tomita J  ', 'Torque    ', 'UfO 4 M   ', 'UKG BC    ', 'UKG2 BC   ', 'V-Acid#4 M', 'V-Acid#7 M', 'V_Acid#9 M', 'VCS 3a J  ', 'videoG1 zs', 'videoG2 zs', 'videoG4 zs', 'waowLd zs ', 'Weazel M  ', 'WetThn zs ', 'Siren BC  ', 'Wobble M  ', 'xPandr zs ', 'yahy zs   ', 'Yeao! M   ', 'ZartPad J ', 'Zupfi J   ', 'Wobbler AV', 'RevShot AV', '-Init-    '
    ],
    'ROM-U': [
        'AccMW JL  ', 'AfterpadCC', 'AM Keys BC', 'Andy´sGR @', '=<*| CM"  ', 'ArtifactJL', 'AstralPdJL', 'AT FrqPdBC', 'B@dRezo   ', ')~%=+ CM  ', 'Bell6th @ ', 'Bellt@ble ', 'BelzBelz @', 'Bone JL   ', '+,. CM    ', 'Chant JL  ', 'Curtain BC', 'DigiBel6 @', 'DlayVerb!@', ',~J>{ CM  ', 'DoomBellJL', 'EmKayEss@ ', 'EPPGp@+Bel', 'EvilNoyzM@', ';<*|´ CM" ', 'Flys CC   ', 'GlitchHit@', 'H@acker   ', 'J@peE.Ate ', ';<+ CM"   ', 'L@byrinth ', 'LFOhB@by  ', 'M@trix1000', 'ModelA100@', '<`[^] CM  ', 'Mr.Kite @ ', 'MrKitinaJL', 'NghtTme JL', 'Pad 4AD XM', '=;:-+ CM  ', 'Positiv JL', 'PPGWavesCC', 'Ramped BC ', 'S@y TI" " ', '=<* CM    ', 'Scores jh ', 'Sick 2 CL ', 'SpcMonkyJL', 'Spirits JL', '`[/ CM    ', '>=.)*^ CM ', 'StutrVoxBC', 'SwmpThngBC', '_)+´ CM   ', 'Table@ir  ', 'The Val.jh', '~`/> CM   ', 'Tiam@t    ', 'TortrPadBC', '~*/>* CM  ', 'TransqilSV', 'TrncslidSV', ',.)´ CM   ', '>:´ CM"   ', 'Two keysSV', 'Vampyr @  ', '´) CM"    ', 'VilePad JL', '´*´)CM"  ', 'VolesGrng@', 'Voyager JL', 'Warped JL ', 'Xu@rn     ', ';<.- CM   ', 'VocoPad XM', 'VOC five  ', 'VOC osc 1 ', 'VOC pad   ', 'VOC pwm   ', 'VOC waves ', 'VOC crisp ', 'VOC tube  ', 'VOC walker', 'VOC noise ', 'VOC reso  ', 'VOCrevers', 'VOC bell 1', 'VOC twelve', 'VOC narrow', 'VOC diffus', 'VOC lfo   ', 'VOC bell 2', 'VOC four  ', 'VOC three ', 'VOC two   ', 'VOC one   ', 'SplddVOCJL', 'INP clean ', 'INP lowpas', 'INP reso  ', 'INP hipass', 'INP bandps', 'INPdouble', 'INP flange', 'INP key   ', 'INP keyfol', 'INP pad   ', 'INP arp   ', 'INP sat   ', 'INP amp   ', 'INP shaper', 'LOOPKILL1b', 'LOOPKILL2b', 'LOOPKILL3b', 'FLWTHIS01b', 'FLWTHIS02b', 'LP FadeATM', 'HP FadeATM', 'LP FadeATM', 'DubEchoATM', 'Evil ATM  ', 'AT>PhasATM', 'AT>PhasATM', 'AT>RedxATM', 'AT>RctfATM', '<Rect ATM ', 'Raw ATM   ', '-INIT- ATM'
    ],
    'ROM-V': [
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty'
        ],
    'ROM-W': [
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty'
    ],
    'ROM-X': [
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty'
    ],
    'ROM-Y': [
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty'
    ],
    'ROM-Z': [
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 
        'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty', 'Empty'
    ],
}

def escape_xml(text):
    """Escape special XML characters"""
    return (text.replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;'))

def generate_midnam():
    """Generate complete MIDNAM XML"""
    xml = '''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MIDINameDocument PUBLIC "-//MIDI Manufacturers Association//DTD MIDINameDocument 1.0//EN" "http://www.midi.org/dtds/MIDINameDocument10.dtd">
<MIDINameDocument>
  <Author>Steffen Klein</Author>
  <MasterDeviceNames>
    <Manufacturer name="Access">
      <Model name="Virus TI2">
        <Description>Access Virus TI2 (Firmware 5.1.3.0)</Description>
        <ChannelNameSet InitialBankMSB="0" InitialBankLSB="0" InitialProgram="0">
          <ChannelName Number="1">Single Mode</ChannelName>
'''
    
    # ROM Banks
    rom_banks = [
        ('ROM-A', 0, 0),
        ('ROM-B', 0, 1),
        ('ROM-C', 0, 2),
        ('ROM-D', 0, 3),
        ('ROM-E', 0, 4),
        ('ROM-F', 0, 5),
        ('ROM-G', 0, 6),
        ('ROM-H', 0, 7),
        ('ROM-I', 0, 8),
        ('ROM-J', 0, 9),
        ('ROM-K', 0, 10),
        ('ROM-L', 0, 11),
        ('ROM-M', 0, 12),
        ('ROM-N', 0, 13),
        ('ROM-O', 0, 14),
        ('ROM-P', 0, 15),
        ('ROM-Q', 0, 16),
        ('ROM-R', 0, 17),
        ('ROM-S', 0, 18),
        ('ROM-T', 0, 19),
        ('ROM-U', 0, 20),
        ('ROM-V', 0, 21),
        ('ROM-W', 0, 22),
        ('ROM-X', 0, 23),
        ('ROM-Y', 0, 24),
        ('ROM-Z', 0, 25),
    ]
    
    # RAM Banks
    ram_banks = [
        ('RAM-A', 1, 0),
        ('RAM-B', 1, 1),
        ('RAM-C', 1, 2),
        ('RAM-D', 1, 3),
    ]
    
    all_banks = rom_banks + ram_banks
    
    for bank_name, msb, lsb in all_banks:
        xml += f'          <PatchBank Name="{bank_name}" MSB="{msb}" LSB="{lsb}">\n'
        xml += '            <PatchNameList>\n'
        
        # Get presets (or generate empty ones)
        if bank_name in PRESETS:
            presets = PRESETS[bank_name]
        else:
            presets = [f'Patch {i}' for i in range(128)]
        
        for i in range(128):
            name = presets[i] if i < len(presets) else f'Patch {i}'
            name_escaped = escape_xml(name)
            xml += f'              <Patch Number="{i}" Name="{name_escaped}"/>\n'
        
        xml += '            </PatchNameList>\n'
        xml += '          </PatchBank>\n'
    
    xml += '''        </ChannelNameSet>
      </Model>
    </Manufacturer>
  </MasterDeviceNames>
</MIDINameDocument>
'''
    return xml

if __name__ == '__main__':
    xml_content = generate_midnam()
    
    # Save to file
    with open('AccessVirusTI2.midnam', 'w', encoding='utf-8') as f:
        f.write(xml_content)
    
    print("✓ MIDNAM file generated: AccessVirusTI2.midnam")
    print(f"✓ Size: {len(xml_content)} bytes")
    print("\nNächste Schritte:")
    print("1. Speichere die Datei im richtigen Verzeichnis deiner DAW:")
    print("   - Cubase: <Cubase>/Definitions/")
    print("   - Logic Pro: ~/Library/Application Support/Logic/Midi Devices/")
    print("   - Studio One: Extensions/Manufacturer Definitions/")
    print("2. Starte deine DAW neu")
    print("3. Der Virus TI2 sollte jetzt alle Presetnamen anzeigen")
